/* Action types */
const ADD_CLASS = 'ADD_CLASS';
const HIGHLIGHT_CLASS = 'HIGHLIGHT_CLASS';
const DEHIGHLIGHT_CLASS = 'DEHIGHLIGHT_CLASS';
const DELETE_CLASS = 'DELETE_CLASS';

export { ADD_CLASS, HIGHLIGHT_CLASS, DELETE_CLASS, DEHIGHLIGHT_CLASS };
