/* Action types */
const ADD_CLASS = 'ADD_CLASS';
const HIGHLIGHT_CLASS = 'HIGHLIGHT_CLASS';
const DEHIGHLIGHT_CLASS = 'DEHIGHLIGHT_CLASS';
const DELETE_CLASS = 'DELETE_CLASS';
const BIO_MAJOR = 'BIO_MAJOR';
const CHEM_MAJOR = 'CHEM_MAJOR';
const CROSS_CULTURAL_ANALYSIS = 'CROSS_CULTURAL_ANALYSIS';
const CULTURAL_DIVERSITY_IN_THE_US = 'CULTURAL_DIVERSITY_IN_THE_US';
const HISTORY_AND_TRADITION = 'HISTORY_AND_TRADITION';

const CHANGE_VIEW = 'CHANGE_VIEW';

export { ADD_CLASS, HIGHLIGHT_CLASS, DELETE_CLASS, DEHIGHLIGHT_CLASS, BIO_MAJOR, CHEM_MAJOR, CHANGE_VIEW, CROSS_CULTURAL_ANALYSIS, CULTURAL_DIVERSITY_IN_THE_US, HISTORY_AND_TRADITION };
