/* Action types */
const ADD_CLASS = 'ADD_CLASS';
const HIGHLIGHT_CLASS = 'HIGHLIGHT_CLASS';
const DEHIGHLIGHT_CLASS = 'DEHIGHLIGHT_CLASS';
const DELETE_CLASS = 'DELETE_CLASS';
const BIO_MAJOR = 'BIO_MAJOR';
const CHEM_MAJOR = 'CHEM_MAJOR';

export { ADD_CLASS, HIGHLIGHT_CLASS, DELETE_CLASS, DEHIGHLIGHT_CLASS, BIO_MAJOR, CHEM_MAJOR};
